ERROR: 2025-05-29 15:49:53,872 | signals | Message: Error while process request /uk/: 
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\contrib\sessions\backends\base.py", line 244, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = middleware_method(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Projects\hillel_django_hw5\hillel_project\general\middlewares.py", line 21, in process_view
    if request.user.is_authenticated and not request.path.startswith("/admin"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\contrib\auth\middleware.py", line 39, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\contrib\auth\middleware.py", line 19, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\contrib\auth\__init__.py", line 304, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\contrib\auth\__init__.py", line 95, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\contrib\sessions\backends\base.py", line 249, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\contrib\sessions\backends\db.py", line 55, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_session
ERROR: 2025-05-29 15:50:18,441 | signals | Message: Error while process request /admin/: 
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\contrib\sessions\backends\base.py", line 244, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = middleware_method(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Projects\hillel_django_hw5\hillel_project\general\middlewares.py", line 21, in process_view
    if request.user.is_authenticated and not request.path.startswith("/admin"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\contrib\auth\middleware.py", line 39, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\contrib\auth\middleware.py", line 19, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\contrib\auth\__init__.py", line 304, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\contrib\auth\__init__.py", line 95, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\contrib\sessions\backends\base.py", line 249, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\contrib\sessions\backends\db.py", line 55, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\hillel-django-DUqsLS4x-py3.12\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_session
